config/routes.rb
# Application routes definition
Rails.application.routes.draw do

  # User actions
  resource :users,  only: [:create, :show]

  # Session actions
  resource :sessions, only: [:create, :show, :destroy]

  # Tiny URL actions
  resource :urls, only: [:create, :show]
  get '/:tiny_path', to: 'urls#access'

  # Root path
  root 'home#index'
end

app/models/url.rb
# Url model
class Url < ActiveRecord::Base
  # Validation
  web_regex = /(?:http|https):\/\/[a-z0-9]+(?:[\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(?:(?::[0-9]{1,5})?\/[^\s]*)?/ix

  validates :path,
            :presence => { :message => 'is required' },
            :format   => { :with => web_regex, :message => 'is in incorrect format'}

  validates :tiny_path,
            :presence => { :message => 'is required' },
            :uniqueness => { :case_sensitive => false, :message => 'has to be unique' }

  # tiny_url initialization
  before_validation :shorten_url, on: :create

  # Relations
  belongs_to :user

  # Generate shortened Url
  def shorten_url
    self.tiny_path ||= SecureRandom.urlsafe_base64(5)[0, 5].downcase
  end
end

app/models/user.rb
# User model
class User < ActiveRecord::Base
  # bcrypt authentication support
  has_secure_password

  # Validation
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email,
            :presence => { :message => 'is required' },
            :format   => { :with => email_regex, :message => 'is in incorrect format'},
            :uniqueness => { :case_sensitive => false, :message => 'you provided is already taken' }

  validates :password,
            :presence => { :message => 'is required' },
            :length => { in: 6..40, :message => 'should be at least 6 characters and not greater than 20 characters in length' },
            :on => :create

  # Access token initialization
  before_validation :update_token, on: :create

  # Relations
  has_many :urls

  # Perform sign-in
  def signin
    self.update_token
    self.save!
  end

  # Perform sign-out
  def signout
    self.access_token = nil
    self.save!
  end

  # Is signed in ?
  def signedin?
    !self.access_token.nil?
  end

  # Generate default token
  def update_token
    self.access_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
# Base Application Controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Error handling
  rescue_from Exception, :with => :handle_error

  # Authentication handler
  def authorize
    token = request.headers['Access-Token']
    @current_user ||= User.find_by(:access_token => token) if token

    render json: { message: 'Invalid access token'  }, status: :unauthorized unless @current_user
  end

  private
  # Error handler
  def handle_error(e)
    render json: { message: e.message }, status: :unprocessable_entity and return
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
# Sessions controller
class SessionsController < ApplicationController

  # Skip CSRF for JSON
  skip_before_filter :verify_authenticity_token

  # Authorization
  before_filter :authorize, :only => :destroy

  # Show sign up form
  def show
  end

  # Sign-in action
  def create
    user = User.find_by_email(session_params[:email])

    # If the user exists AND the password entered is correct.
    if user && user.authenticate(session_params[:password])
      user.signin

      render json: { access_token: user.access_token, email: user.email }, status: :ok
    else
      render json: { message: 'Incorrect email or password'  }, status: :unauthorized
    end
  end

  # Sign-out action
  def destroy
    if @current_user
      @current_user.signout

      @current_user = nil

      render json: { message: 'success' }, status: :ok
    else
      render json: { message: 'No permission for this method'  }, status: :unauthorized
    end
  end

  # Parameters sanitization
  private

  def session_params
    params.require(:session).permit(:email, :password, :access_token)
  end
end

app/controllers/urls_controller.rb
# Urls conroller
class UrlsController < ApplicationController
  # Skip CSRF for JSON
  skip_before_filter :verify_authenticity_token

  # Authorization
  before_filter :authorize, :only => :create

  # Add URL form
  def show
  end

  # Add new URL
  def create
    url = Url.new(url_params)
    url.user = @current_user
    if url.save
      render json: { tiny_path: url.tiny_path }, status: :ok
    else
      render json: { message: url.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # Render redirection to tiny URL or show an error message
  def access
    if params['tiny_path'].length == 5
      url = Url.find_by(:tiny_path => params['tiny_path'])
      if url
        redirect_to url.path
      else
        @error_message = 'Tiny URL not found'
      end
    else
      @error_message = 'Invalid tiny URL'
    end
  end

  # Parameters sanitization
  private

  def url_params
    params.require(:url).permit(:path)
  end

end

app/controllers/users_controller.rb
# Users controller
class UsersController < ApplicationController

  # Skip CSRF for JSON
  skip_before_filter :verify_authenticity_token

  # Show sign up form
  def show
  end

  # Create new user / Sign-up
  def create
    user = User.new(user_params)
    if user.save
      render json: { id: user.id, email: user.email }, status: :ok
    else
      render json: { message: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  # Parameters sanitization
  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/views/home/index.html.haml
.center.jumbotron
  .h1 Welcome to URL Shortener

  %p Please sign-up or sign-in in order be able to shorten your urls

  = link_to "Sign up", users_path, :class => 'btn btn-lg btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title URL Shortener Tool
    %meta{ :charset => 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge' }
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1' }
    %meta{ :name => 'keywords', :content => 'URL Shortener, Short Urls, Tiny Urls' }
    %meta{ :name => 'description', :content => 'URL Shortener tool, generates short version of URLs and allows to open them.' }

    = stylesheet_link_tag    "application", :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    / Header
    = render 'shared/header'

    / Content
    .container
      = yield

    / Footer
    = render 'shared/footer'

app/views/shared/_footer.html.haml
%footer.footer
  .container.small
    .pull-left
      URL Shortener tool by
      =link_to 'Vitaliy Yatsunyk', 'http://github.com/djvit', :target => '_blank'

    %ul.pull-right
      %li= link_to "Sign Up", users_path, :class => 'lnk_noauth'
      %li= link_to "Sign In", sessions_path, :class => 'lnk_noauth'
      %li= link_to "Shorten URL", urls_path, :class => 'lnk_auth'
      %li= link_to "Log Out", '#', :class => 'lnk_auth', :id => 'btn_sign_out'

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top
  .container

    =link_to 'URL Shortener', '/', :id => 'logo'

    %ul.nav.navbar-nav.navbar-right
      %li= link_to "Sign Up", users_path, :class => 'lnk_noauth'
      %li= link_to "Sign In", sessions_path, :class => 'lnk_noauth'
      %li= link_to "Shorten URL", urls_path, :class => 'lnk_auth'
      %li= link_to "Log Out", '#', :class => 'lnk_auth', :id => 'btn_sign_out'

app/views/urls/access.html.haml
.center.jumbotron
  .h2
    ERROR:
    =@error_message

  %p Please add a new URL if you want to access its shortened version

  = link_to "Add URL", '#', :class => 'btn btn-lg btn-primary'

app/views/urls/show.html.haml
.center.jumbotron
  .h2 Add an URL to shorten
  %form{ :role => 'form' }
    .form-group
      %label{ :for => 'url' } Web address:
      %input.form-control{ :type =>'text', :id => 'url', :name => 'url[path]', :placeholder => 'http://www.someweb.com' }

      %button.btn.btn-lg.btn-primary{ :id => 'btn_add_url'} Add URL

  %br
  .h3.hidden{ :id => 'tiny_url_result' }
    Shortened URL:
    =link_to '', '#', :id => 'lnk_url_result', :target => '_blank'

app/views/users/show.html.haml
.center.jumbotron
  .h2 Sign Up
  %form{ :role => 'form' }
    .form-group
      %label{ :for => 'user_name' } User name:
      %br

      %input.form-control.short{ :type =>'email', :id => 'email', :name => 'user[email]', :placeholder => 'email' }
      %br
      %br

      %label{ :for => 'password' } Password:
      %br

      %input.form-control.short{ :type =>'password', :id => 'password', :name => 'user[password]', :placeholder => 'password' }
      %br


      %button.btn.btn-lg.btn-primary{ :id => 'btn_sign_up'} Sign Up